// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcojvrgliprloqzzftik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjb2p2cmdsaXBybG9xenpmdGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTMwMTcsImV4cCI6MjA2NTI2OTAxN30.0a9UBlxdw7coaleDrKDlBV5V7qcTFIhDfUrDeL1yjkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);