// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vodvfkqjhzyytasulsgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZHZma3FqaHp5eXRhc3Vsc2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTcyOTYsImV4cCI6MjA2NTI3MzI5Nn0.olYeh-YBqWT2ZtZ5hVUAf5dvDITI6pfj3Qdy_UyOCUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);